# config.yaml
vault_root: "obsidian_vault"
default_folder: "8_Miscellaneous"

category_rules:
  "characters": "1_People"
  "locations": "2_Locations"
  "factions": "3_Factions"
  "items": "4_Items"
  "races": "5_Races"
  "lore": "6_Lore"
  "magic": "7_Magic"
  "dragons": "1_People"

subcategory_rules:
  "locations":
    - "ruins"
    - "settlements":
      - "cities"
      - "towns"
      - "roads"
    - "establishments"
    - "nations"
    - "wilderness":
      - "forests"
      - "mountains"
      - "seas"
      - "wetlands"
    - "fortifications"
    - "continents"

  "factions":
    - "houses"

  "items":
    - "weapons"
    - "minerals"
    - "flora"

  "lore":
    - "history"
    - "mythology"
    - "languages"
    - "religion"
    - "conflicts"
    - "holidays"

tag_consolidation:
  # Fortifications
  "forts": "fortifications"
  "castles": "fortifications"

  # Factions & Power Structures
  "institutions": "factions"
  "organisations": "factions"
  "military_units": "factions"
  "mercenary_bands": "factions"
  "notable_families": "houses"
  "familys": "houses"
  "guilds": "factions"
  "noble_houses": "houses"
  "crime": "factions"
  "factionss": "factions"
  "governments": "factions"

  # Settlements
  "settlement": "towns"
  "towns_and_villages": "towns"
  "baronies": "towns"
  "human_realms": "nations"
  "elven_realms": "nations"
  "dwarven_kingdoms": "nations"
  "territorial_regions": "nations"
  "national_governmentss": "nations"
  "palinor": "commonwealth"
  "greystone": "valand"
  "republic_of_ilia": "ilia"
  "urenos": "locations"

  # Establishments
  "inns": "establishments"
  "brothels": "establishments"
  "fighting_pits": "establishments"

  # Wilderness
  "mountain_ranges": "mountains"
  "lakes": "wetlands"
  "deserts": "wilderness"

  # Conflicts
  "wars": "conflicts"
  "battles": "conflicts"
  "dragon_conquest": "conflicts"
  "leontini_wars": "conflicts"

  # Lore
  "ancient_civilizations": "history"
  "time": "lore"
  "documents": "history"
  "events": "history"

  # Cultures & Races
  "elves": "races"

  # Items & Equipment
  "artifacts": "items"
  "runeblades": "weapons"
  "technology": "items"
  "plantss": "flora"

  # Magic & Realms
  "feywild": "magic"
  "spirit_world": "magic"
  "creatures": "magic"

  # Characters
  "players": "characters"