# config.yaml
vault_root: "obsidian_vault"
default_folder: "8_Miscellaneous"

category_rules:
  "characters": "1_People"
  "locations": "2_Locations"
  "factions": "3_Factions"
  "items": "4_Items"
  "races": "5_Races"
  "lore": "6_Lore"
  "magic": "7_Magic"
  "dragons": "1_People"

subcategory_rules:
  "2_Locations":
    "cities": "Cities"
    "towns": "Towns"
    "establishments": "Establishments"
    "nations": "Nations"
    "wilderness": "Wilderness"
    "ruins": "Ruins"
    "continents": "Continents"
    "roads": "Roads"
    "fortifications": "Fortifications"
  "3_Factions":
    "nobility": "Nobility"
  "4_Items":
    "weapons": "Weapons"
    "minerals": "Minerals"
    "flora": "Flora"
  "6_Lore":
    "mythology": "Mythology"
    "languages": "Languages"
    "religion": "Religion"
    "conflicts": "Conflicts"
    "events": "Events"
    "holidays": "Holidays"

tag_consolidation:
  # Fortifications
  "forts": "fortifications"
  "castles": "fortifications"

  # Factions & Power Structures
  "institutions": "factions"
  "organisations": "factions"
  "military_units": "factions"
  "mercenary_bands": "factions"
  "notable_families": "factions"
  "guilds": "factions"
  "noble_houses": "factions"

  # Settlements
  "settlement": "towns"
  "towns_and_villages": "towns"
  "baronies": "towns"
  "human_realms": "nations"
  "elven_realms": "nations"
  "dwarven_kingdoms": "nations"
  "territorial_regions": "nations"

  # Establishments
  "inns": "establishments"
  "brothels": "establishments"
  "fighting_pits": "establishments"

  # Wilderness
  "mountain_ranges": "wilderness"
  "islands": "wilderness"
  "deserts": "wilderness"
  "forests": "wilderness"
  "lakes": "wilderness"
  "seas": "wilderness"

  # Conflicts
  "wars": "conflicts"
  "battles": "conflicts"
  "dragon_conquest": "conflicts"
  "leontini_wars": "conflicts"

  # History
  "ancient_civilizations": "history"

  # Cultures & Races
  "elves": "races"

  # Items & Equipment
  "artifacts": "items"
  "runeblades": "weapons"

  # Magic & Realms
  "feywild": "magic"
  "spirit_world": "magic"
  "creatures": "magic"

  # Characters
  "players": "characters"